env:
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build

task:
  name: "Gradle"
  stateful: true
  timeout_in: 120m
  container:
    image: anggit86/android-sdk:latest
    cpu: 8
    memory: 32G

  Clone_script:
    - git clone --depth 1 https://github.com/Blawuken/MicroG-Extended MicroG-Extended
  tests_script:
    - cd MicroG-Extended
    - ./gradlew assemble
  release_script:
    - cd MicroG-Extended
    - ./gradlew assembleRelease
