env:
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build

task:
  name: "Gradle"
  stateful: true
  timeout_in: 120m
  container:
    image: reactivecircus/android-sdk:latest
    cpu: 8
    memory: 32G

  clone_repo:
    git clone https://github.com/Blawuken/MicroG-Extended $CIRRUS_WORKING_DIR/MicroG-Extended
  # assemble while emulator is starting
  tests_script:
    - cd $CIRRUS_WORKING_DIR/MicroG-Extended
    - ./gradlew assemble
  release_script:
    - cd $CIRRUS_WORKING_DIR/MicroG-Extended
    - ./gradlew assembleRelease
