env:
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build

task:
  name: "Gradle"
  stateful: true
  timeout_in: 120m
  container:
    image: cirrusci/android-sdk:30
    cpu: 8
    memory: 32G

  create_device_script: >
    echo no | avdmanager create avd --force \
        -n test \
        -k "system-images;android-18;default;armeabi-v7a"
  start_emulator_background_script: >
    $ANDROID_HOME/emulator/emulator \
        -avd test \
        -no-audio \
        -no-window
  Clone_script:
    - mkdir -p Test && cd Test
    - git clone --depth 1 https://github.com/Blawuken/MicroG-Extended MicroG-Extended
  # assemble while emulator is starting
  tests_script:
    - cd Test/MicroG-Extended
    - ./gradlew assemble
  release_script:
    - cd Test/MicroG-Extended
    - ./gradlew assembleRelease
