task:
  name: "Gradle"
  stateful: true
  timeout_in: 120m
  container:
    image: ghcr.io/cirruslabs/android-sdk:34
    cpu: 8
    memory: 32G

  install_emulator_script:
    sdkmanager --install "system-images;android-34;google_apis;x86"
  create_avd_script:
    echo no | avdmanager create avd --force
      -n emulator
      -k "system-images;android-34;google_apis;x86"
  start_avd_background_script:
    $ANDROID_HOME/emulator/emulator
      -avd emulator
      -no-audio
      -no-boot-anim
      -gpu swiftshader_indirect
      -no-snapshot
      -no-window
  clone_repo:
    git clone https://github.com/Blawuken/MicroG-Extended
  # assemble while emulator is starting
  tests_script:
    - cd MicroG-Extended
    - ./gradlew assemble
  release_script:
    - cd MicroG-Extended
    - ./gradlew assembleRelease
