task:
  name: "Gradle"
  stateful: true
  timeout_in: 120m
  container:
    image: reactivecircus/android-sdk:latest
    cpu: 8
    memory: 32G

  clone_repo:
    git clone https://github.com/Blawuken/MicroG-Extended MicroG-Extended
  # assemble while emulator is starting
  tests_script:
    - ls -all
    - cd MicroG-Extended
    - ./gradlew assemble
  release_script:
    - cd MicroG-Extended
    - ./gradlew assembleRelease
