name: Building dependencies

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.1'
        cache: false

    - name: Setup Android environment
      uses: android-actions/setup-android@v3

    - name: Build dependencies
      run: |
        mkdir ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        git clone --depth=1 https://github.com/SagerNet/sing-box.git
        cd sing-box
        make
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init
        go mod tidy -v
        gomobile bind -v -androidapi 27 -ldflags='-s -w' ./
        echo "======================================="
        ls -all
        echo "======================================="