name: Canvas Node Test

on: 
  push:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Install dependency node
      run: |
        npm install

    - name: Test
      run: |
        node test.js

    - name: Update Nightly TAG
      uses: richardsimko/update-tag@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly

    - name: Uload to Release
      uses: meeDamian/github-release@2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: nightly
        commitish: ${{ github.sha }}
        name: Nightly Release
        body: >
          apalah cuman gabut.
        draft: false
        prerelease: true
        files: >
          canvas/Jb1.png
        gzip: folders
        allow_override: true
