name: Canvas Node Test

on: 
  push:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x

    - name: Install dependency node
      run: |
        npm install

    - name: Test
      run: |
        node test.js
