name: Canvas Node Test

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  update-nightly:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetching tags
      run: git fetch --tags -f || true

    - name: Setup Node
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x

    - name: Install dependency node
      run: |
        npm install

    - name: Test
      run: |
        node test.js

    - name: Update Nightly TAG
      uses: richardsimko/update-tag@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly
    