name: Canvas Node Test

permissions:
  contents: write

on:
  push:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetching tags
      run: git fetch --tags -f || true

    - name: Setup Node
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x

    - name: Install dependency node
      run: |
        npm install

    - name: Test
      run: |
        node test.js & sleep 2s

    - name: Anu crot
      run: |
        ls canvas/*

    - name: Update Nightly Release
      uses: meeDamian/github-release@2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: nightly
        commitish: ${{ github.sha }}
        name: Nightly Release
        body: >
          Gabut.
        draft: false
        prerelease: true
        files: >
          canvas/OnePiece.png
        gzip: folders
        allow_override: true
    