name: UbuntuSSH

on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: JDK Setup
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8

    - name: Setup Java
      run: echo "JAVA_HOME=$JAVA_HOME_8_X64" >> $GITHUB_ENV

    - name: Session Setup
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 300
      with:
        sudo: true
