name: UbuntuSSH

on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: anggit86/ubuntu:asoy

    steps:
    - uses: actions/checkout@v3

    - name: Session Setup
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 300
      with:
        sudo: true
