name: Anjay

on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: anasty17/mltb:latest

    steps:
    - uses: actions/checkout@v3

    - name: Test Build.. ⏳
      run: |
        git clone https://Blawuken:$GITHUB_TOKEN@github.com/Blawuken/mirror-leech-telegram-bot anjay && cd anjay
        pip3 install --upgrade pip wheel setuptools
        pip3 install --no-cache-dir -r requirements-cli.txt
        pip3 install --no-cache-dir -r requirements.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
