name: Anjay

on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: anasty17/mltb:latest

    steps:
    - uses: actions/checkout@v3

    - name: Test Build.. ⏳
      run: |
        rm -rfd /usr/src/app
        git clone https://Blawuken:${GH_ANU}@github.com/Blawuken/mirror-leech-telegram-bot /usr/src/app && cd /usr/src/app
        pip3 install --upgrade pip wheel setuptools
        pip3 install --no-cache-dir -r requirements-cli.txt
        pip3 install --no-cache-dir -r requirements.txt
        bash start.sh
      env:
        GH_ANU: ${{ secrets.GH_ANU }}
