name: App Sign

on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "zulu"

    - name: Sign APK
      id: sign_apk
      uses: ilharp/sign-android-release@v1
      with:
        releaseDir: app
        signingKey: ${{ secrets.SIGNING_KEY }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyAlias: ${{ secrets.ALIAS }}
        keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

    # Example use of `signedReleaseFile` output -- not needed
    - uses: actions/upload-artifact@v2
      with:
        name: Signed app bundle
        path: app/*.apk
